---
abstract: 'Use the Freedesktop.org base directory specification'
author:
  - 'Jaap Karssenberg || Pardus [Larus] <pardus@cpan.org>'
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  File::Which: '0'
  Test::More: '0.98'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.022, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-BaseDir
requires:
  Exporter: '5.57'
  IPC::System::Simple: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/uperl/File-BaseDir/issues
  homepage: https://metacpan.org/pod/File::BaseDir
  repository: git://github.com/uperl/File-BaseDir.git
version: '0.09'
x_generated_by_perl: v5.34.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
x_use_unsafe_inc: 0
